services:
  db:
    image: postgres:16-alpine
    container_name: beauty_salon_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - beauty_salon_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: he1l2u/beauty-salon-coursework:01
    container_name: beauty_salon_app
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      AppSettings__SalonName: MusyaBeauty
      AppSettings__SalonAddress: г. Москва, ул. Примерная, д. 1
      AppSettings__WorkTime: 09:00-20:00
    ports:
      - "8001:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  beauty_salon_pgdata:
